### ISSUE TITLE
While running "ern run-ios" :  throws error

### ISSUE THREAD

**Issue by AnkitaBonny** [electrode-io/electrode-native#1104]
(node:32291) UnhandledPromiseRejectionWarning: Error: XCode xcbuild command failed with exit code 65
    at ChildProcess.xcodebuildProc.on.code (/Users/a0m0344/.ern/versions/0.29.7/node_modules/ern-orchestrator/src/buildIosRunner.ts:29:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:32291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by belemaire** [comment]
When facing such an error (`XCode xcbuild command failed with exit code ...`) you should open the iOS project in XCode (the project that is inside the `ios` directory) and build it from XCode.
Unfortunately, the `xcbuild` command that Electrode Native uses to build the iOS project does not give much logs in term of what failed, so the only way to get more details about the cause of the failure is to build the project directly in XCode.
