### ISSUE TITLE
App Crashed upon launch due to missing libhermes.so

### ISSUE THREAD

**Issue by santhoshgutta** [electrode-io/electrode-native#1375]
The app crashed upon launch due to missing libhermes.co JNI library. This occurred when the container was migrated to use RN v0.60.5.

The app works fine in emulators, but not in devices. Also occurs in release version only.

About to load: libhermes.so
10-23 14:52:40.010 29557 29600 D SoLoader: libhermes.so not found on /data/data/com.test.app/lib-main
10-23 14:52:40.010 29557 29600 D SoLoader: libhermes.so not found on /data/app/com.test.app-20ZOSCIM6fKUYumUTKxclA==/lib/arm64
10-23 14:52:40.010 29557 29600 D SoLoader: libhermes.so not found on /vendor/lib
10-23 14:52:40.010 29557 29600 D SoLoader: libhermes.so not found on /system/lib
10-23 14:52:40.013 29557 29600 E SoLoader: couldn't find DSO to load: libhermes.so
10-23 14:52:40.015 29557 29600 E AndroidRuntime: FATAL EXCEPTION: create_react_context
10-23 14:52:40.015 29557 29600 E AndroidRuntime: Process: com.test.app, PID: 29557
10-23 14:52:40.015 29557 29600 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.soloader.SoLoader.b(SoLoader.java:738)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.soloader.SoLoader.a(SoLoader.java:591)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.soloader.SoLoader.a(SoLoader.java:529)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.soloader.SoLoader.a(SoLoader.java:484)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.hermes.reactexecutor.a.create(HermesExecutorFactory.java:27)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at com.facebook.react.k$5.run(ReactInstanceManager.java:949)
10-23 14:52:40.015 29557 29600 E AndroidRuntime:     at java.lang.Thread.run(Thread.java:764)
10-23 14:52:40.020  1134  2918 W ActivityManager:   Force finishing activity com.test.app/com.test.app.screens.activities.MainActivity

**Comment by santhoshgutta** [comment]
The app crash was fixed by adding `hermes-release.aar` in `app/libs` folde, and `libfb.so` in `jniLibs\arm64-v8a`, `jniLibs\armeabi-v7a`, `jniLibs\x86`, `jniLibs\x86_64`

**Comment by santhoshgutta** [comment]
I was able to find `hermes-release.aar` from `node_modules⁩\⁨hermes-engine⁩\android⁩`

**Comment by deepueg** [comment]
@santhoshgutta Thanks for reporting this. We will add support for this in the next release.
