### ISSUE TITLE
create-container command throws an error

### ISSUE THREAD

**Issue by airamrguez** [electrode-io/electrode-native#1396]
After running `ern create-container` the step _Generate Composite from Cauldron_ throws an error.

![Captura de pantalla 2019-11-07 a las 12 14 38](https://user-images.githubusercontent.com/1159448/68384637-48e5f000-0158-11ea-9ef6-1f109b68f934.png)

**Comment by airamrguez** [comment]
A trace of the error

```sh
➜  tmp ERN_LOG_LEVEL=trace ern create-container
 ___ _        _               _       _  _      _   _
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.38.7] [Cauldron: test-cauldron]

pwd
pwd
[ Connecting to the Cauldron (Started) ]
[BaseGit] Syncing /Users/myusername/.ern/cauldron
[BaseGit] Fetching from upstream master
[BaseGit] Syncing /Users/myusername/.ern/cauldron
[BaseGit] Fetching from upstream master
[ Connecting to the Cauldron (Completed in 1s)]
? Choose a native application version MyApp:ios:0.0.1
[ Ensuring that native application descriptor exists in Cauldron (Started) ]
[ Ensuring that native application descriptor exists in Cauldron (Completed in 0s)]
[ Generating Composite from Cauldron (Started) ]
[ Generating Composite (Started) ]
generateComposite config : {
  "jsApiImplDependencies": [],
  "miniApps": [],
  "outDir": "/var/folders/j5/28jm0t0568ncdvfwvykf6kjh0000gp/T/tmp-79674N6zxKtlHvkyJ"
}
[ Cleaning up existing composite directory (Started) ]
[ Cleaning up existing composite directory (Completed in 0s)]
pushd /var/folders/j5/28jm0t0568ncdvfwvykf6kjh0000gp/T/tmp-79674N6zxKtlHvkyJ
/private/var/folders/j5/28jm0t0568ncdvfwvykf6kjh0000gp/T/tmp-79674N6zxKtlHvkyJ /Users/myusername/tmp
[generateComposite] no yarn lock provided
[runYarnCommand] Running /Users/myusername/.ern/versions/0.38.7/node_modules/ern-core/node_modules/.bin/yarn init --yes
execp => command: /Users/myusername/.ern/versions/0.38.7/node_modules/ern-core/node_modules/.bin/yarn init --yes options: undefined
yarn init v1.19.1

warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.

success Saved package.json

Done in 0.02s.

popd
/Users/myusername/tmp
[ Generating Composite (Failed) ]
✖ runCauldronCompositeGen failed: TypeError: Cannot convert undefined or null to object
[ Generating Composite from Cauldron (Failed) ]
✖ An error occurred: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/myusername/.ern/versions/0.38.7/node_modules/ern-composite-gen/src/generateComposite.ts:240:35
    at Generator.next (<anonymous>)
    at fulfilled (/Users/myusername/.ern/versions/0.38.7/node_modules/ern-composite-gen/dist/generateComposite.js:5:58)
```

**Comment by belemaire** [comment]
Hi @airamrguez 

Thanks for the trace :+1:

The error you are facing, is due to the fact that the command you are running (`create-container`) is trying to create an empty container (with no MiniApps -and/or JS API implementations- to put into).

Can see this in the log ...
```
"jsApiImplDependencies": [],  
"miniApps": []
```

... which means that you haven't added any MiniApp to your `MyApp:ios:0.0.1` version in Cauldron.

There is no point in generating a Container that does't contain anything (no MiniApps or JS API implementations), so the command should fail in any case.

That being said, it fails ungracefully, because this case is not properly handled (it was at some point, so a regression has been introduced in some release). 

We will fix this so that it fails with a clear informative error message rather than an obscure side effect exception.
