### ISSUE TITLE
`miniapp` command error

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode-native#143]
Any calls to the `ern miniapp <whatever>` command result in errors:

```shell
ern miniapp --help
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.7.0] [Cauldron: -NONE-]

Error: ENOENT: no such file or directory, scandir '/Users/c0r00jl/.ern/versions/0.7.0/node_modules/ern-local-cli/dist/commands/miniapp'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at requireDirectory (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/require-directory/index.js:59:6)
    at Object.self.addDirectory (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/yargs/lib/command.js:113:33)
    at Object.Yargs.self.commandDir (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/yargs/yargs.js:343:13)
    at Object.exports.builder (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/ern-local-cli/src/commands/miniapp.js:6:16)
    at Object.self.runCommand (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/yargs/lib/command.js:193:35)
    at Object.Yargs.self._parseArgs (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/yargs/yargs.js:930:19)
    at Object.run [as default] (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/ern-local-cli/src/index.js:54:10)
    at Object.<anonymous> (/Users/c0r00jl/.ern/versions/0.7.0/node_modules/ern-local-cli/src/index.prod.js:3:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at runLocalCli (/Users/c0r00jl/Projects/electrode-native/global-cli/src/index.js:123:5)
    at Object.<anonymous> (/Users/c0r00jl/Projects/electrode-native/global-cli/src/index.js:40:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/c0r00jl/Projects/electrode-native/global-cli/bin/ern.js:2:1)
```

The `miniapp` command appears in the `ern --help` output:

![miniwat](https://user-images.githubusercontent.com/1858316/31191150-239c109c-a8f2-11e7-9815-69a74ac21bec.jpg)

Does this command do anything? Maybe it should be removed. Also, non-existing commands probably shouldn't throw `fs.readdir` errors.

**Comment by belemaire** [comment]
Yes this command was deprecated a while ago but we forgot to remove it.

It has been noticed and fixed in a recent commit https://github.com/electrode-io/electrode-native/commit/83fd031c4ce40183481863bae2f113e726fa7b78

Will disappear in `ern 0.8.0` to be released on Monday.
