### ISSUE TITLE
System tests failing

### ISSUE THREAD

**Issue by friederbluemle** [electrode-io/electrode-native#1488]
Not entirely sure when it started happening, but a fresh clone of the `master` branch is failing system tests with the following error:

```
[ react-native-ernmovie-api-impl is not declared in the manifest. Performing additional checks. (Completed in 0s)]
One or more native dependencies identified: [{"path":"tmp/node_modules/react-native-electrode-bridge","packagePath":{"basePath":"react-native-electrode-bridge","version":"1.5.23","fullPath":"react-native-electrode-bridge@1.5.23"}},{"path":"tmp/node_modules/react-native-ernmovie-api","packagePath":{"basePath":"react-native-ernmovie-api","version":"0.0.11","fullPath":"react-native-ernmovie-api@0.0.11"}},{"path":"tmp/node_modules/react-native-ernmovie-api-impl","packagePath":{"basePath":"react-native-ernmovie-api-impl","version":"0.0.16","fullPath":"react-native-ernmovie-api-impl@0.0.16"}}]
✖ An error occurred: [Transitive Dependency] react-native-electrode-bridge@1.5.23 was not added to the MiniApp
Error: [Transitive Dependency] react-native-electrode-bridge@1.5.23 was not added to the MiniApp
    at MiniApp.<anonymous> (./ern-core/src/MiniApp.ts:48:36)
    at Generator.next (<anonymous>)
    at fulfilled (./ern-core/dist/MiniApp.js:1:35005)
!!! TEST FAILED !!!  add react-native-ernmovie-api-impl@0.0.16
Expected exit code 0 but command exited with code 1
```

Using `1000.0.0` of ern

Related: #1485

**Comment by friederbluemle** [comment]
With https://github.com/electrode-io/electrode-native-manifest/pull/158 merged, the build is green again.
