### ISSUE TITLE
Error when initializing ElectrodeReactContainer

### ISSUE THREAD

**Issue by marcosjuniorzup** [electrode-io/electrode-native#1531]
I already apologize for my English not being so good,
I'm from Brazil, and I'm migrating an application that we have in native (iOS and Android) to React Native.
In my miniapp I am using git approach, and during application startup after putting:
```java
ElectrodeReactContainer.initialize(
  this as Application,
  ElectrodeReactContainer.Config()
)
```
I'm having this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 31902
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.ClassCastException: com.example.myapplication.MainActivity cannot be cast to android.app.Application
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassCastException: com.example.myapplication.MainActivity cannot be cast to android.app.Application
        at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:21)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

My generated submodule: https://github.com/marcosjuniorzup/sdk-web-publisher
My main activity:
```kotlin
package com.example.myapplication

import android.app.Application
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import com.walmartlabs.ern.container.miniapps.SdkMobileMiniAppActivity
import com.walmartlabs.ern.container.ElectrodeReactContainer



class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        ElectrodeReactContainer.initialize(
            this as Application,
            ElectrodeReactContainer.Config()
        )

        val button = findViewById(R.id.main_button) as Button

        button.setOnClickListener {
            val intent = Intent(this, SdkMobileMiniAppActivity::class.java)
            startActivity(intent)
        }

    }

}
```

**Comment by LcTwisk** [comment]
The first param should really be an instance of the Application class (see: [Application](https://developer.android.com/reference/android/app/Application)). Just doing an unsafe cast using `as! Application` will only fool the compiler.

Personally, I've just put the initialization of the container in my custom application class. You probably already have such a class in the app. If [this](https://medium.com/@balakrishnanpt/android-application-class-a8a1d64c82d1), might be useful:

**Comment by friederbluemle** [comment]
Hi @marcosjuniorzup - @LcTwisk is correct, you cannot cast an Activity to an Application.

You should **move** the following section _out_ of your `Activity` class, and _into_ your `Application` class:

```kotlin
// MainActivity.kt
//...
        ElectrodeReactContainer.initialize(
            this as Application,
            ElectrodeReactContainer.Config()
        )
```

```kotlin
// App.kt
class App : Application() {
    override fun onCreate() {
        super.onCreate()

        ElectrodeReactContainer.initialize(
            this,
            ElectrodeReactContainer.Config()
        )
    }
}
```

If `com.example.myapplication` does not have a file for the application class yet, you need to add it first (and also declare it in `AndroidManifest.xml`).

**Comment by marcosjuniorzup** [comment]
Eu já alterei isso, e coloquei na issue, mas ainda estou tendo problemas com o Fragment, tive que fazer esse workaround https://github.com/electrode-io/electrode-native/issues/1363

**Comment by friederbluemle** [comment]
@marcosjuniorzup - Can you post some more details about the problems with Fragment?
