### ISSUE TITLE
Android app crashes on navigating back from MiniApps

### ISSUE THREAD

**Issue by faisalmohd83** [electrode-io/electrode-native#1789]
Hi,

The generated container includes all miniapps and attached to the Android native app as a library (submodule). The MiniApps are accessible and navigating to the same using startActivity(). the forward navigation works partially but on Back button/action from miniapp crashes with below exception:

```
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.facebook.react.ReactDelegate.onBackPressed()' on a null object reference
        at com.facebook.react.ReactActivityDelegate.onBackPressed(ReactActivityDelegate.java:140)
        at com.walmartlabs.ern.container.ElectrodeMiniAppActivity.onBackPressed(ElectrodeMiniAppActivity.java:96)
        at android.app.Activity.onKeyUp(Activity.java:3644)
        at com.walmartlabs.ern.container.ElectrodeMiniAppActivity.onKeyUp(ElectrodeMiniAppActivity.java:113)
       
```

Also, noticed the below issue while navigating to miniapps from native.

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostPause()' on a null object reference
        at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:95)
        at com.walmartlabs.ern.container.ElectrodeReactActivityDelegate.onPause(ElectrodeReactActivityDelegate.java:230)
        at com.walmartlabs.ern.container.ElectrodeMiniAppActivity.onPause(ElectrodeMiniAppActivity.java:70)
        at android.app.Activity.performPause(Activity.java:7985)
```

**Comment by faisalmohd83** [comment]
@deepueg @friederbluemle 

Following [android-showcase](https://github.com/electrode-io/electrode-native-showcaseapp-android/blob/master/app/src/main/java/com/walmartlabs/ern/showcase/MainActivity.java) tutorial, the `ReactActivityDelegate` is unable to access from `ElectrodeReactActivityDelegate.BackKeyHandler` in `ElectrodeCoreActivity`.
