### ISSUE TITLE
ElectrodeContainer iOS build failed, module cli.js not found

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#560]
Doing clean build, using ERN platform 0.12.2. When trying to build the generated ElectrodeContainer framework for iOS project with Xcode 9.2, there is a sudden terminal popup with error note:

```javascript

module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/jmiettunen/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
Process terminated. Press <enter> to close the window
```

I haven't seen this before, I think it's new with ERN platform 0.12.2.

Btw the error note is correct, there is no such folder. If it should exist, what settings do I need to modify to get it there? The whole ~/.enr folder and it's contents were generated by ERN commands.

**Comment by clairewli** [comment]
@jomnius Thanks for reporting the issue. This is a known unblocking issue. You can just ignore the pop-up. When you run `ern run-ios`, as long as you get a `Build Succeeded` in the end, you should be good to go. This pop-up is some noise from React Native itself.

**Comment by jomnius** [comment]
Thanx, but I'm not able to use `ern run-ios`. Will ignore the popup anyway!

This case can be closed.
